package fr;

// Generated 24 mars 2016 16:11:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "brand", catalog = "assurance")
public class Brand implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set models = new HashSet(0);

	public Brand() {
	}

	public Brand(String name) {
		this.name = name;
	}

	public Brand(String name, Set models) {
		this.name = name;
		this.models = models;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "brand")
	public Set<Model> getModels() {
		return this.models;
	}

	public void setModels(Set<Model> models) {
		this.models = models;
	}

}
