package entity;

// Generated 22 mars 2016 11:08:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set models = new HashSet(0);

	public Brand() {
	}

	public Brand(String name) {
		this.name = name;
	}

	public Brand(String name, Set models) {
		this.name = name;
		this.models = models;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getModels() {
		return this.models;
	}

	public void setModels(Set models) {
		this.models = models;
	}

}
