package fr;

// Generated 24 mars 2016 16:11:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "assurance")
public class Client implements java.io.Serializable {

	private Integer id;
	private User user;
	private int bonus;
	private Date drivingLicenceDate;
	private int accidentNumber;
	private boolean isSecondary;
	private Set quotes = new HashSet(0);

	public Client() {
	}

	public Client(User user, int bonus, Date drivingLicenceDate,
			int accidentNumber, boolean isSecondary) {
		this.user = user;
		this.bonus = bonus;
		this.drivingLicenceDate = drivingLicenceDate;
		this.accidentNumber = accidentNumber;
		this.isSecondary = isSecondary;
	}

	public Client(User user, int bonus, Date drivingLicenceDate,
			int accidentNumber, boolean isSecondary, Set quotes) {
		this.user = user;
		this.bonus = bonus;
		this.drivingLicenceDate = drivingLicenceDate;
		this.accidentNumber = accidentNumber;
		this.isSecondary = isSecondary;
		this.quotes = quotes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "bonus", nullable = false)
	public int getBonus() {
		return this.bonus;
	}

	public void setBonus(int bonus) {
		this.bonus = bonus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "drivingLicenceDate", nullable = false, length = 19)
	public Date getDrivingLicenceDate() {
		return this.drivingLicenceDate;
	}

	public void setDrivingLicenceDate(Date drivingLicenceDate) {
		this.drivingLicenceDate = drivingLicenceDate;
	}

	@Column(name = "accidentNumber", nullable = false)
	public int getAccidentNumber() {
		return this.accidentNumber;
	}

	public void setAccidentNumber(int accidentNumber) {
		this.accidentNumber = accidentNumber;
	}

	@Column(name = "isSecondary", nullable = false)
	public boolean isIsSecondary() {
		return this.isSecondary;
	}

	public void setIsSecondary(boolean isSecondary) {
		this.isSecondary = isSecondary;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "quoteuser", catalog = "assurance", joinColumns = { @JoinColumn(name = "userId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "quoteId", nullable = false, updatable = false) })
	public Set<Quote> getQuotes() {
		return this.quotes;
	}

	public void setQuotes(Set<Quote> quotes) {
		this.quotes = quotes;
	}

}
