package fr;

// Generated 22 mars 2016 11:08:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Habitation generated by hbm2java
 */
public class Habitation implements java.io.Serializable {

	private Integer id;
	private String type;
	private double surface;
	private int roomNumber;
	private int floor;
	private int bathroomNumber;
	private boolean garage;
	private Double groundSurface;
	private double patioSurface;
	private String heatingType;
	private String option;
	private Set quotes = new HashSet(0);

	private Address address;

	public Habitation() {
	}

	public Habitation(String type, double surface, int roomNumber,
			int bathroomNumber, boolean garage, double patioSurface,
			String heatingType, String option) {
		this.type = type;
		this.surface = surface;
		this.roomNumber = roomNumber;
		this.bathroomNumber = bathroomNumber;
		this.garage = garage;
		this.patioSurface = patioSurface;
		this.heatingType = heatingType;
		this.option = option;
	}

	public Habitation(String type, double surface, int roomNumber,
			int floor, int bathroomNumber, boolean garage,
			Double groundSurface, double patioSurface, String heatingType,
			String option, Set quotes) {
		this.type = type;
		this.surface = surface;
		this.roomNumber = roomNumber;
		this.floor = floor;
		this.bathroomNumber = bathroomNumber;
		this.garage = garage;
		this.groundSurface = groundSurface;
		this.patioSurface = patioSurface;
		this.heatingType = heatingType;
		this.option = option;
		this.quotes = quotes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public double getSurface() {
		return this.surface;
	}

	public void setSurface(double surface) {
		this.surface = surface;
	}

	public int getRoomNumber() {
		return this.roomNumber;
	}

	public void setRoomNumber(int roomNumber) {
		this.roomNumber = roomNumber;
	}

	public int getFloor() {
		return this.floor;
	}

	public void setFloor(int floor) {
		this.floor = floor;
	}

	public int getBathroomNumber() {
		return this.bathroomNumber;
	}

	public void setBathroomNumber(int bathroomNumber) {
		this.bathroomNumber = bathroomNumber;
	}

	public boolean isGarage() {
		return this.garage;
	}

	public void setGarage(boolean garage) {
		this.garage = garage;
	}

	public Double getGroundSurface() {
		return this.groundSurface;
	}

	public void setGroundSurface(Double groundSurface) {
		this.groundSurface = groundSurface;
	}

	public double getPatioSurface() {
		return this.patioSurface;
	}

	public void setPatioSurface(double patioSurface) {
		this.patioSurface = patioSurface;
	}

	public String getHeatingType() {
		return this.heatingType;
	}

	public void setHeatingType(String heatingType) {
		this.heatingType = heatingType;
	}

	public String getOption() {
		return this.option;
	}

	public void setOption(String option) {
		this.option = option;
	}

	public Set getQuotes() {
		return this.quotes;
	}

	public void setQuotes(Set quotes) {
		this.quotes = quotes;
	}

	public Address getAddress() { return address; }

	public void setAddress(Address address) { this.address = address; }

}
