package fr;

// Generated 24 mars 2016 16:11:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Model generated by hbm2java
 */
@Entity
@Table(name = "model", catalog = "assurance")
public class Model implements java.io.Serializable {

	private Integer id;
	private Brand brand;
	private String name;
	private Set vehicles = new HashSet(0);

	public Model() {
	}

	public Model(Brand brand, String name) {
		this.brand = brand;
		this.name = name;
	}

	public Model(Brand brand, String name, Set vehicles) {
		this.brand = brand;
		this.name = name;
		this.vehicles = vehicles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brandId", nullable = false)
	public Brand getBrand() {
		return this.brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "model")
	public Set<Vehicle> getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Set<Vehicle> vehicles) {
		this.vehicles = vehicles;
	}

}
