package fr;

// Generated 22 mars 2016 11:08:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Quote generated by hbm2java
 */
public class Quote implements java.io.Serializable {

	private Integer id;
	private Vehicle vehicle;
	private Habitation habitation;
	private String name;
	private int step;
	private boolean isCompleted;
	private double price;
	private String summary;
	private Set users = new HashSet(0);

	public Quote() {
	}

	public Quote(String name, int step, boolean isCompleted, double price,
			String summary) {
		this.name = name;
		this.step = step;
		this.isCompleted = isCompleted;
		this.price = price;
		this.summary = summary;
	}

	public Quote(Vehicle vehicle, Habitation habitation, String name, int step,
			boolean isCompleted, double price, String summary, Set users) {
		this.vehicle = vehicle;
		this.habitation = habitation;
		this.name = name;
		this.step = step;
		this.isCompleted = isCompleted;
		this.price = price;
		this.summary = summary;
		this.users = users;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public Habitation getHabitation() {
		return this.habitation;
	}

	public void setHabitation(Habitation habitation) {
		this.habitation = habitation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getStep() {
		return this.step;
	}

	public void setStep(int step) {
		this.step = step;
	}

	public boolean isIsCompleted() {
		return this.isCompleted;
	}

	public void setIsCompleted(boolean isCompleted) {
		this.isCompleted = isCompleted;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
