package fr;

// Generated 24 mars 2016 16:11:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Vehicle generated by hbm2java
 */
@Entity
@Table(name = "vehicle", catalog = "assurance")
public class Vehicle implements java.io.Serializable {

	private Integer id;
	private Address address;
	private Model model;
	private String fuel;
	private String horsepower;
	private boolean sleepInside;
	private boolean anyRisk;
	private Set quotes = new HashSet(0);

	public Vehicle() {
	}

	public Vehicle(Address address, Model model, String fuel,
			String horsepower, boolean sleepInside, boolean anyRisk) {
		this.address = address;
		this.model = model;
		this.fuel = fuel;
		this.horsepower = horsepower;
		this.sleepInside = sleepInside;
		this.anyRisk = anyRisk;
	}

	public Vehicle(Address address, Model model, String fuel,
			String horsepower, boolean sleepInside, boolean anyRisk, Set quotes) {
		this.address = address;
		this.model = model;
		this.fuel = fuel;
		this.horsepower = horsepower;
		this.sleepInside = sleepInside;
		this.anyRisk = anyRisk;
		this.quotes = quotes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "addressId", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelId", nullable = false)
	public Model getModel() {
		return this.model;
	}

	public void setModel(Model model) {
		this.model = model;
	}

	@Column(name = "fuel", nullable = false, length = 45)
	public String getFuel() {
		return this.fuel;
	}

	public void setFuel(String fuel) {
		this.fuel = fuel;
	}

	@Column(name = "horsepower", nullable = false, length = 45)
	public String getHorsepower() {
		return this.horsepower;
	}

	public void setHorsepower(String horsepower) {
		this.horsepower = horsepower;
	}

	@Column(name = "sleepInside", nullable = false)
	public boolean isSleepInside() {
		return this.sleepInside;
	}

	public void setSleepInside(boolean sleepInside) {
		this.sleepInside = sleepInside;
	}

	@Column(name = "anyRisk", nullable = false)
	public boolean isAnyRisk() {
		return this.anyRisk;
	}

	public void setAnyRisk(boolean anyRisk) {
		this.anyRisk = anyRisk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicle")
	public Set<Quote> getQuotes() {
		return this.quotes;
	}

	public void setQuotes(Set<Quote> quotes) {
		this.quotes = quotes;
	}

}
